In [57]:
# To plot inline
%matplotlib inline

# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [152]:
data_train = pd.read_csv('train.csv')
print('Number Of Rows: {}'.format(len(data_train)))
print('--------------------------')
data_train.head()

Number Of Rows: 891
--------------------------


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [153]:
for x in ['Name','Ticket','Cabin','Embarked','Fare']: del data_train[x]
data_train.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch
0            1         0       3    male  22.0      1      0
1            2         1       1  female  38.0      1      0
2            3         1       3  female  26.0      0      0
3            4         1       1  female  35.0      1      0
4            5         0       3    male  35.0      0      0

In [154]:
data_train.Sex = data_train.Sex.astype('category').cat.codes
data_train.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch
0            1         0       3    1  22.0      1      0
1            2         1       1    0  38.0      1      0
2            3         1       3    0  26.0      0      0
3            4         1       1    0  35.0      1      0
4            5         0       3    1  35.0      0      0

In [155]:
data_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Sex               int8
Age            float64
SibSp            int64
Parch            int64
dtype: object

In [156]:
data_train.dropna(inplace=True)
print(data_train.isnull().values.any())
print('----------------------------------')
print('Number Of Rows: {}'.format(len(data_train)))

False
----------------------------------
Number Of Rows: 714


In [157]:
nmbr = data_train.groupby('Survived').count()['PassengerId']
nmbr

Survived
0    424
1    290
Name: PassengerId, dtype: int64

In [158]:
print('%.2f percent of total people survided.\n%.2f percent people died.'%(nmbr[1]*100/(nmbr[1] + nmbr[0]),nmbr[0]*100/(nmbr[1] + nmbr[0])))

40.62 percent of total people survided.
59.38 percent people died.


In [159]:
data_train['FamilySize'] = data_train.SibSp + data_train.Parch
del data_train['SibSp']
del data_train['Parch']
target = data_train['Survived'].copy() 
data_train

PassengerId  Survived  Pclass  Sex   Age  FamilySize
0              1         0       3    1  22.0           1
1              2         1       1    0  38.0           1
2              3         1       3    0  26.0           0
3              4         1       1    0  35.0           1
4              5         0       3    1  35.0           0
6              7         0       1    1  54.0           0
7              8         0       3    1   2.0           4
8              9         1       3    0  27.0           2
9             10         1       2    0  14.0           1
10            11         1       3    0   4.0           2
11            12         1       1    0  58.0           0
12            13         0       3    1  20.0           0
13            14         0       3    1  39.0           6
14            15         0       3    0  14.0           0
15            16         1       2    0  55.0           0
16            17         0       3    1   2.0           5
18            19         0       3    0  31.0           1
20            21         0       2    1  35.0           0
21            22         1       2    1  34.0           0
22            23         1       3    0  15.0           0
23            24         1       1    1  28.0           0
24            25         0       3    0   8.0           4
25            26         1       3    0  38.0           6
27            28         0       1    1  19.0           5
30            31         0       1    1  40.0           0
33            34         0       2    1  66.0           0
34            35         0       1    1  28.0           1
35            36         0       1    1  42.0           1
37            38         0       3    1  21.0           0
38            39         0       3    0  18.0           2
..           ...       ...     ...  ...   ...         ...
856          857         1       1    0  45.0           2
857          858         1       1    1  51.0           0
858          859         1       3    0  24.0           3
860          861         0       3    1  41.0           2
861          862         0       2    1  21.0           1
862          863         1       1    0  48.0           0
864          865         0       2    1  24.0           0
865          866         1       2    0  42.0           0
866          867         1       2    0  27.0           1
867          868         0       1    1  31.0           0
869          870         1       3    1   4.0           2
870          871         0       3    1  26.0           0
871          872         1       1    0  47.0           2
872          873         0       1    1  33.0           0
873          874         0       3    1  47.0           0
874          875         1       2    0  28.0           1
875          876         1       3    0  15.0           0
876          877         0       3    1  20.0           0
877          878         0       3    1  19.0           0
879          880         1       1    0  56.0           1
880          881         1       2    0  25.0           1
881          882         0       3    1  33.0           0
882          883         0       3    0  22.0           0
883          884         0       2    1  28.0           0
884          885         0       3    1  25.0           0
885          886         0       3    0  39.0           5
886          887         0       2    1  27.0           0
887          888         1       1    0  19.0           0
889          890         1       1    1  26.0           0
890          891         0       3    1  32.0           0

[714 rows x 6 columns]

In [160]:
gender_survival = data_train.groupby(['Survived','Sex']).count()['PassengerId']
gender_survival

Survived  Sex
0         0       64
          1      360
1         0      197
          1       93
Name: PassengerId, dtype: int64

In [135]:
pw_survided = gender_survival.iloc[1]*100/(gender_survival.iloc[1] + gender_survival.iloc[0])
pm_died = gender_survival.iloc[2]*100/(gender_survival.iloc[2] + gender_survival.iloc[3])
print('%.2f percent of the total survived are women and %.2f of the total died are men'%(pw_survided,pm_died))

84.91 percent of the total survived are women and 67.93 of the total died are men


In [161]:
del data_train['PassengerId']
del data_train['Survived']
data_train

Pclass  Sex   Age  FamilySize
0         3    1  22.0           1
1         1    0  38.0           1
2         3    0  26.0           0
3         1    0  35.0           1
4         3    1  35.0           0
6         1    1  54.0           0
7         3    1   2.0           4
8         3    0  27.0           2
9         2    0  14.0           1
10        3    0   4.0           2
11        1    0  58.0           0
12        3    1  20.0           0
13        3    1  39.0           6
14        3    0  14.0           0
15        2    0  55.0           0
16        3    1   2.0           5
18        3    0  31.0           1
20        2    1  35.0           0
21        2    1  34.0           0
22        3    0  15.0           0
23        1    1  28.0           0
24        3    0   8.0           4
25        3    0  38.0           6
27        1    1  19.0           5
30        1    1  40.0           0
33        2    1  66.0           0
34        1    1  28.0           1
35        1    1  42.0           1
37        3    1  21.0           0
38        3    0  18.0           2
..      ...  ...   ...         ...
856       1    0  45.0           2
857       1    1  51.0           0
858       3    0  24.0           3
860       3    1  41.0           2
861       2    1  21.0           1
862       1    0  48.0           0
864       2    1  24.0           0
865       2    0  42.0           0
866       2    0  27.0           1
867       1    1  31.0           0
869       3    1   4.0           2
870       3    1  26.0           0
871       1    0  47.0           2
872       1    1  33.0           0
873       3    1  47.0           0
874       2    0  28.0           1
875       3    0  15.0           0
876       3    1  20.0           0
877       3    1  19.0           0
879       1    0  56.0           1
880       2    0  25.0           1
881       3    1  33.0           0
882       3    0  22.0           0
883       2    1  28.0           0
884       3    1  25.0           0
885       3    0  39.0           5
886       2    1  27.0           0
887       1    0  19.0           0
889       1    1  26.0           0
890       3    1  32.0           0

[714 rows x 4 columns]

In [165]:
X = data_train.as_matrix()
print(X)
y = target.as_matrix()
print(y)

[[  3.   1.  22.   1.]
 [  1.   0.  38.   1.]
 [  3.   0.  26.   0.]
 ..., 
 [  1.   0.  19.   0.]
 [  1.   1.  26.   0.]
 [  3.   1.  32.   0.]]
[0 1 1 1 0 0 0 1 1 1 1 0 0 0 1 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 1 0 0 1 1 0 0
 0 1 1 0 1 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0 1 1 0 1 0 1 1 0 1 0 0 0 0 0 0
 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0
 0 1 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 1
 1 0 0 1 0 1 1 1 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 1 1 0 1 0 1 0 0 1 0 1 0 0
 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 1
 0 0 1 0 0 0 1 0 1 0 1 1 1 1 0 0 0 0 0 1 0 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0
 1 1 1 0 1 1 1 0 0 0 0 1 1 0 1 1 0 0 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1
 0 0 0 0 1 0 0 0 1 1 0 1 0 0 1 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 1 0 1 1
 1 1 0 0 0 0 0 0 1 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 1 1 1 1 0 0 1 1 0 1 1 0
 0 0 0 0 1 0 1 1 0 0 0 0 1 0 0 1 1 1 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 0 1 1
 1 1 0 0 1 1 0 1 0 1 0 1 0 0 

In [284]:
from sklearn.ensemble import RandomForestClassifier,ExtraTreesClassifier,GradientBoostingClassifier,VotingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV,StratifiedKFold,train_test_split

In [290]:
n_splits = 4

svc_params = {'C':[0.9,1,1.5,10]}

rfc_params = {'n_estimators':[30,40],
              'min_samples_split':[10,20],
              'random_state':[10,15],
              'warm_start':(True,False)
             }

etc_params = {'n_estimators':[20,40],
              'min_samples_split':[10,20,50],
              'random_state':[10,15,30],
              'warm_start':(True,False),
              'criterion' : ('gini','entropy')
             }

gbc_params = {  'learning_rate':[0.1,0.15],
              'n_estimators':[10,50,80],
              'max_depth':[3,8,10],
              'warm_start':(True,False),
              'subsample' : [0.5,0.8,1.0]
             }
dtc_params = {'criterion':('gini','entropy'),
             'splitter':('best','random'),
              'max_depth':[5,10,15,None],
              'min_samples_split':[2,5,10]
             }
vtc_params = {'voting': ('hard','soft'),
             
      }


In [291]:
skf = StratifiedKFold(n_splits=n_splits)

# clf1 = SVC()
# clf1 = GridSearchCV(clf1,svc_params,cv=skf,verbose=1,n_jobs=2)
# clf1.fit(X,y)

# clf2 = RandomForestClassifier()
# clf2 = GridSearchCV(clf2,rfc_params,cv=skf,verbose=1,n_jobs=2)
# clf2.fit(X,y)

# clf3 = ExtraTreesClassifier()
# clf3 = GridSearchCV(clf3,etc_params,cv=skf,verbose=1,n_jobs=2)
# clf3.fit(X,y)

# clf4 = GradientBoostingClassifier()
# clf4 = GridSearchCV(clf4,gbc_params,cv=skf,verbose=1,n_jobs=2)
# clf4.fit(X,y)

# clf5 = DecisionTreeClassifier()
# clf5 = GridSearchCV(clf5,dtc_params,cv=skf,verbose=1,n_jobs=2)
# clf5.fit(X,y)

clf6 = VotingClassifier(estimators = [('svc',clf1),('rfc',clf2),('etc',clf3),('gbc',clf4),('dtc',clf5)])
clf6 = GridSearchCV(clf6,vtc_params,cv=skf,verbose=1,n_jobs=2)
clf6.fit(X,y)

# models = [x.best_estimator_ for x in [clf1,clf2,clf3,clf4,clf5,clf6]]
# scores = [x.best_score_ for x in [clf1,clf2,clf3,clf4,clf5,clf6]]



# print('Training Score : %0.2f'%clf1.score(X_train,y_train))
# print('Testing Score : %0.2f'%clf1.score(X_test,y_test))

# for tr_index,ts_index in skf.split(X,y):
#     clf1 = SVC()
#     clf1 = GridSearchCV(clf1,svc_params)
#     X_train = X[tr_index]
#     X_test = X[ts_index]
#     y_train = y[tr_index]
#     y_test = y[ts_index]
    
#     clf1.fit(X_train,y_train)
#     print('Training Score : %0.2f'%clf1.score(X_train,y_train))
#     print('Testing Score : %0.2f'%clf1.score(X_test,y_test))
    

AttributeError: 'GridSearchCV' object has no attribute 'best_estimator_'

In [289]:
print(clf6.best_score_)
print('----------------------------')
clf6.best_estimator_

NotFittedError: This GridSearchCV instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

In [283]:
print(clf5.best_score_)
print('----------------------------')
clf5.best_estimator_

0.819327731092
----------------------------


DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=10,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=5, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [280]:
print(clf4.best_score_)
print('----------------------------')
clf4.best_estimator_

0.827731092437
----------------------------


GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=8,
              max_features=None, max_leaf_nodes=None,
              min_impurity_split=1e-07, min_samples_leaf=1,
              min_samples_split=2, min_weight_fraction_leaf=0.0,
              n_estimators=10, presort='auto', random_state=None,
              subsample=0.5, verbose=0, warm_start=True)

In [237]:
print(clf3.best_score_)
print('----------------------------')
clf3.best_estimator_

0.822128851541
----------------------------


ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='entropy',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=20, min_weight_fraction_leaf=0.0,
           n_estimators=40, n_jobs=1, oob_score=False, random_state=10,
           verbose=0, warm_start=True)

In [229]:
print(clf2.best_score_)
print('----------------------------')
clf2.best_estimator_

{'split0_test_score': array([ 0.7877095 ,  0.7877095 ,  0.77094972,  0.77094972,  0.7877095 ,
        0.7877095 ,  0.77094972,  0.77094972,  0.7877095 ,  0.7877095 ,
        0.76536313,  0.76536313,  0.7877095 ,  0.7877095 ,  0.76536313,
        0.76536313,  0.75977654,  0.75977654,  0.74860335,  0.74860335,
        0.75977654,  0.75977654,  0.74860335,  0.74860335,  0.76536313,
        0.76536313,  0.74301676,  0.74301676,  0.76536313,  0.76536313,
        0.74301676,  0.74301676]), 'split1_test_score': array([ 0.84916201,  0.84916201,  0.84916201,  0.84916201,  0.84916201,
        0.84916201,  0.84916201,  0.84916201,  0.82122905,  0.82122905,
        0.84357542,  0.84357542,  0.82122905,  0.82122905,  0.84357542,
        0.84357542,  0.84357542,  0.84357542,  0.84916201,  0.84916201,
        0.84357542,  0.84357542,  0.84916201,  0.84916201,  0.8547486 ,
        0.8547486 ,  0.84357542,  0.84357542,  0.8547486 ,  0.8547486 ,
        0.84357542,  0.84357542]), 'split2_test_score': ar

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=10, min_weight_fraction_leaf=0.0,
            n_estimators=30, n_jobs=1, oob_score=False, random_state=10,
            verbose=0, warm_start=True)

In [206]:
print(clf1.cv_results_)
print('----------------------------')
print(clf1.best_score_)
print('----------------------------')
clf1.best_estimator_

0.796918767507
----------------------------


SVC(C=1.5, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)